python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.imo.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.unesco.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://ioc-unesco.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iode.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.gebco.net/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/mgg/aboutmgg/oceanmapping.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://ioc.unesco.org/jcomm/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ccop.or.th/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.icsu.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.igu-net.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.geog.umontreal.ca/Commission_maritime_geog/Accueil.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iugg.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iag-aig.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iugg.org/iapso/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iugs.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.fig.net/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.fig.net/commission4/index.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://cartography.tuwien.ac.at/ica/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.abdn.ac.uk/geospatial/ica/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://ica.ign.fr/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.iho-ohi.net/english/home/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/mgg/bathymetry/iho.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.gmat.unsw.edu.au/ablos/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.isprs.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.arcticportal.org/iasc/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.scar.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.scor-int.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.icsu-fags.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.geodesie.ird.fr/bgi/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://igscb.jpl.nasa.gov/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/wdc/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/mgg/wdc/wdcgmg.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.unesco.or.id/activities/science/earth_sci/46.php" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://sclilp.gfz-potsdam.de/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www-odp.tamu.edu/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.sopac.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.bsh.de/de/Meeresdaten/Geodaten/index.jsp" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.bgr.bund.de/cln_011/nn_323774/EN/Themen/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.continentalshelf.org/onestopdatashop.aspx" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://imina.soest.hawaii.edu/HMRG/index.php" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ifremer.fr/sismer/index_FR.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.jamstec.go.jp/dataportal/viewer.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://cats.u-strasbg.fr/geomarines.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.marine-geo.org/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/mgg/geodas/geodas.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ngdc.noaa.gov/mgg/bathymetry/relief.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://map.ngdc.noaa.gov/website/mgg/trackline/viewer.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://map.ngdc.noaa.gov/website/mgg/multibeam/viewer.htm" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www7320.nrlssc.navy.mil/DBDB2_WWW/NRLCOM_dbdb2.html" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ldeo.columbia.edu/res/pi/SCICEX/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://nsdl.sdsc.edu/" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://www.ig.utexas.edu/sdc/cruiseinfo.php" &
python3 vocab_scrap.py --verbose --in=words.json --out=words.json --fork "http://mbdata.whoi.edu/mbdata.html" &